version: '3.8'
services:
    java-maven-app:
      image: vgevorgyan009/demo-app:java-maven-6.0
      ports:
        - 4000:8080
    postgres:
      image: postgres:15
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd
